spring:
  application:
    name: discovery-server
    
eureka:  client:    register-with-eureka: false
    fetch-registry: false
    
  server:
    wait-time-in-ms-when-sync-empty: 0    peer-node-read-timeout-ms: 25000
    
server:  port: 8761
      